CREATE DATABASE SQL_TASK;

USE SQL_TASK;

create table DEPARTMENTS (
	DEPARTMENT_ID nvarchar(255) PRIMARY KEY,
	DEPARTMENT_NAME  nvarchar(255) DEFAULT NULL,
	MANAGER_ID nvarchar(255) NOT NULL,
	LOCATION_ID nvarchar(255) DEFAULT NULL,
);

create table JOBS (
	JOB_ID int PRIMARY KEY,
	JOB_TITLE nvarchar(255) DEFAULT NULL,
	MIN_SALARY int DEFAULT NULL,
	MAX_SALARY int DEFAULT NULL,
);

create table [employee table](
	EMPLOYEE_ID nvarchar(255) DEFAULT NULL,
	FIRST_NAME nvarchar(255) DEFAULT NULL,
	LAST_NAME nvarchar(255) DEFAULT NULL,
	EMAIL nvarchar(255) DEFAULT NULL,
	PHONE_NUMBER nvarchar(255) DEFAULT NULL,
	HIRE_DATE date DEFAULT NULL,
	JOB_ID int NOT NULL FOREIGN KEY REFERENCES JOBS(JOB_ID),
	SALARY int DEFAULT NULL,
	COMMISSION_PCT float DEFAULT NULL,
	MANAGER_ID nvarchar(255) NOT NULL,
	DEPARTMENT_ID nvarchar(255) NOT NULL FOREIGN KEY REFERENCES DEPARTMENTS(DEPARTMENT_ID),
);
